[2022-12-17T04:34:11.690+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ahomework.is_file_correct_task scheduled__2022-01-01T00:02:00+00:00 [queued]>
[2022-12-17T04:34:11.696+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ahomework.is_file_correct_task scheduled__2022-01-01T00:02:00+00:00 [queued]>
[2022-12-17T04:34:11.696+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T04:34:11.696+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-17T04:34:11.696+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T04:34:11.709+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonSensor): is_file_correct_task> on 2022-01-01 00:02:00+00:00
[2022-12-17T04:34:11.715+0000] {standard_task_runner.py:55} INFO - Started process 1659 to run task
[2022-12-17T04:34:11.717+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ahomework', 'is_file_correct_task', 'scheduled__2022-01-01T00:02:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ahomework.py', '--cfg-path', '/tmp/tmp_1d0o97m']
[2022-12-17T04:34:11.718+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask is_file_correct_task
[2022-12-17T04:34:11.767+0000] {task_command.py:389} INFO - Running <TaskInstance: ahomework.is_file_correct_task scheduled__2022-01-01T00:02:00+00:00 [running]> on host 4bef348da8d6
[2022-12-17T04:34:11.833+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ahomework
AIRFLOW_CTX_TASK_ID=is_file_correct_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:02:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-01T00:02:00+00:00
[2022-12-17T04:34:11.834+0000] {python.py:72} INFO - Poking callable: <function is_file_correct at 0x7f28b70dd5f0>
[2022-12-17T04:34:15.844+0000] {python.py:72} INFO - Poking callable: <function is_file_correct at 0x7f28b70dd5f0>
[2022-12-17T04:34:15.850+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 215, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 4.016710413998226 seconds exceeds the specified timeout of 2.
[2022-12-17T04:34:15.858+0000] {taskinstance.py:1327} INFO - Immediate failure requested. Marking task as FAILED. dag_id=ahomework, task_id=is_file_correct_task, execution_date=20220101T000200, start_date=20221217T043411, end_date=20221217T043415
[2022-12-17T04:34:15.869+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task is_file_correct_task (Sensor has timed out; run duration of 4.016710413998226 seconds exceeds the specified timeout of 2.; 1659)
[2022-12-17T04:34:15.898+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-17T04:34:15.928+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
