[2022-12-17T04:33:58.278+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ahomework.is_file_correct_task scheduled__2022-01-01T00:01:00+00:00 [queued]>
[2022-12-17T04:33:58.287+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ahomework.is_file_correct_task scheduled__2022-01-01T00:01:00+00:00 [queued]>
[2022-12-17T04:33:58.287+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T04:33:58.287+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-17T04:33:58.287+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T04:33:58.300+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonSensor): is_file_correct_task> on 2022-01-01 00:01:00+00:00
[2022-12-17T04:33:58.306+0000] {standard_task_runner.py:55} INFO - Started process 1625 to run task
[2022-12-17T04:33:58.309+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ahomework', 'is_file_correct_task', 'scheduled__2022-01-01T00:01:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/ahomework.py', '--cfg-path', '/tmp/tmprw9f93ai']
[2022-12-17T04:33:58.310+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask is_file_correct_task
[2022-12-17T04:33:58.365+0000] {task_command.py:389} INFO - Running <TaskInstance: ahomework.is_file_correct_task scheduled__2022-01-01T00:01:00+00:00 [running]> on host 4bef348da8d6
[2022-12-17T04:33:58.426+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ahomework
AIRFLOW_CTX_TASK_ID=is_file_correct_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:01:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-01T00:01:00+00:00
[2022-12-17T04:33:58.427+0000] {python.py:72} INFO - Poking callable: <function is_file_correct at 0x7f28b70dc560>
[2022-12-17T04:34:02.437+0000] {python.py:72} INFO - Poking callable: <function is_file_correct at 0x7f28b70dc560>
[2022-12-17T04:34:02.444+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 215, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 4.017059086007066 seconds exceeds the specified timeout of 2.
[2022-12-17T04:34:02.451+0000] {taskinstance.py:1327} INFO - Immediate failure requested. Marking task as FAILED. dag_id=ahomework, task_id=is_file_correct_task, execution_date=20220101T000100, start_date=20221217T043358, end_date=20221217T043402
[2022-12-17T04:34:02.470+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task is_file_correct_task (Sensor has timed out; run duration of 4.017059086007066 seconds exceeds the specified timeout of 2.; 1625)
[2022-12-17T04:34:02.489+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-17T04:34:02.516+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
